src/components/Contexts/Variables/VariablesProvider.tsx, src/components/Layout/Navbar/Navbar.tsx, src/components/Token/Login.scss, src/components/Token/Token.tsx, src/gql/ApolloConfigs.ts, src/gql/odb/Observation.ts, src/main.tsx, src/types.d.ts
Added view login-like to upload an ODB service token meanwhile the real authentication is under construction
=> Odb token input

src/components/Contexts/Variables/VariablesProvider.tsx, src/components/Token/Token.tsx, src/types.d.ts
Changed useEffect to useSyncExternalStore hook
=> Odb token hook

src/components/Panels/Guider/Diagram/Diagram.tsx
There was an issue with the diagram being in an infinite re-render loop. Which caused the flow diagram to never actually show. Using different reactflow hooks solves it (and saves on CPU 😅).
=> Fix diagram constant rerendering

src/gql/server/Buttons.tsx
Javier complained about not having the slew button.
Added placeholder disabled button.
=> Show a placeholder disabled button

src/Helpers/functions.test.ts, src/Helpers/functions.ts
Related: https://github.com/gemini-hlsw/navigate-configs/pull/7
Maybe we need some sort of shared library?
=> Fix declination values format

src/components/Panels/Guider/LightPath/LightPath.tsx, src/components/Panels/Telescope/Systems/Subsystems.tsx, src/styles/main.scss
Fixed svg and text colors in some under-construction components.
=> Added some missing under construction styles and components

src/gql/server/Buttons.tsx
Added missing variables to request.
Hardcoded issPort and wfs should be modified depending on the UI Port value (instrument section) and WFS from above target selection or guider panel (this should be discussed with Javier)
=> Added variables to instrument request

.github/workflows/node.js.yml, src/components/Panels/Guider/Diagram/Diagram.tsx, src/components/Panels/Guider/Loop/Configuration.tsx, src/components/Panels/Telescope/Targets/GuiderTargets.tsx, src/components/Panels/Telescope/Targets/TargetList.tsx, src/gql/server/Buttons.tsx
Should make it slightly more transparent why things aren't working
=> Add button state to title

src/components/Panels/Guider/Diagram/Diagram.tsx, src/gql/odb/gen/graphql.ts
The WFS nodes are created depending on the configuration data instead of subscription.
Now WFS won't disappear every time a new subscription message is awaited.
=> SC-4467 show WFS in guiding diagram from observation parameters

src/components/Contexts/Variables/Modals/OdbImport/OdbImport.tsx, src/components/Panels/Guider/Alarms/Alarm.test.tsx, src/components/Panels/Guider/Alarms/Alarm.tsx, src/components/Panels/Guider/Alarms/Alarms.test.tsx, src/components/Panels/Guider/Alarms/Alarms.tsx, src/components/Panels/Guider/Alarms/evaluate.test.ts, src/components/Panels/Guider/Alarms/evaluate.ts, src/components/Panels/Guider/Diagram/useGetGuideState.tsx, src/components/Panels/Telescope/Targets/TargetList.tsx, src/components/atoms/alarm.ts, src/components/atoms/atomWithToggle.test.ts, src/components/atoms/atomWithToggle.ts, src/gql/server/GuideState.ts
- **Change text to Enable**
- **Minor changes**
- **Implement new alarm rules**
=> sc 4183 changes to wfs alarms

src/components/Panels/Guider/Diagram/Diagram.tsx
Currently, wfs doesn't change their state unless some other device is using it, which is not reflecting the reality.
=> Change state of wfs even if is not being used

src/components/Panels/Guider/Diagram/Diagram.tsx
Sorry, by mistake I merged the previous PR without this change.
=> Changed in clause to includes to check if source exist

package.json, pnpm-lock.yaml
=> Remove @types/eslint__js

src/components/Panels/Guider/Alarms/Alarm.test.tsx, src/components/Panels/Guider/Alarms/Alarm.tsx, src/components/Panels/Guider/Guider.scss
=> Change enable checkbox to speaker toggle button

src/App.tsx, src/Helpers/toast.tsx, src/components/VersionManager/VersionManager.tsx, src/gql/configs/Version.ts, src/gql/server/Version.ts
https://github.com/user-attachments/assets/bed4bcb3-e130-4d27-a3f6-06d3594b06f7
=> Prompt user to refresh on server version change

.github/workflows/node.js.yml, .npmrc, README.md, package.json, pnpm-lock.yaml, src/components/Icons.tsx, src/gql/server/Buttons.tsx, src/styles/main.scss
Add fontawesome icons to show state
=> Add icons for buttons state

package.json, pnpm-lock.yaml
Reverts gemini-hlsw/navigate-ui#505
=> Revert "chore(deps): update dependency primereact to v10.9.3"

src/gql/ApolloConfigs.ts
I do not know why I didn't see this before.
=> Add reconnection to ws!!

vite.config.ts
=> Add version.txt file to build output

src/components/Panels/WavefrontSensors/WavefrontSensors.scss
=> Colorize warning and debug logs

src/components/Icons.tsx, src/components/Layout/Home/Home.scss, src/components/Panels/Guider/Alarms/Alarms.test.tsx, src/components/Panels/Telescope/Systems/Instrument.test.tsx, src/components/Panels/Telescope/Systems/Instrument.tsx, src/components/Panels/Telescope/Targets/TargetSwapButton.test.tsx, src/components/Shared/Title/Title.tsx, src/gql/configs/Version.ts, src/gql/dev-messages.ts, src/gql/render.tsx, src/gql/server/Version.ts, src/gql/util.ts, src/main.tsx, vite.config.ts
https://github.com/user-attachments/assets/6ff54963-f346-474e-b7d2-aafa72f71f0a
Also adds some type-safety to the graphql mocks.
=> Add button to save instrument parameters

src/gql/ApolloConfigs.ts
I think every ~minute apollo automatically disconnects and reconnects instantly. We don't need to show the disconnected indicator for that. So this adds a 250ms timeout before showing the disconnected indicator.
=> Add a small timeout before showing the disconnected indicator

src/components/Panels/Telescope/Targets/TargetSwapButton.test.tsx, src/components/Panels/Telescope/Targets/TargetSwapButton.tsx
=> Emphasize pointed at guide star button

packages/configs/Dockerfile
Adding prisma generate command to pull openssl lib on docker image build time
=> Configs container loop

packages/ui/src/components/Panels/Guider/Alarms/Alarms.test.tsx, packages/ui/src/components/Panels/Guider/Alarms/Alarms.tsx, packages/ui/src/gql/server/GuideQuality.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Instead of waiting for subscription event to fill the data
=> Query guider quality values right away

packages/ui/.vscode/launch.json, packages/ui/src/components/Panels/Telescope/Systems/Instrument.test.tsx, packages/ui/src/components/Panels/Telescope/Targets/TargetSwapButton.test.tsx, packages/ui/src/components/Panels/WavefrontSensors/AcquisitionCamera/Controls.tsx, packages/ui/src/components/Panels/WavefrontSensors/AcquisitionCamera/TargetsHandset.test.tsx, packages/ui/src/components/Panels/WavefrontSensors/AcquisitionCamera/strategy.ts, packages/ui/vite.config.ts
Also adds a debug configuration to run vitest in debug mode
=> Fix input fields order and add more tests for offset buttons

packages/configs/prisma/migrations/20250904134624_window_center/migration.sql, packages/configs/prisma/schema.prisma, packages/configs/src/graphql/resolvers/WindowCenter.ts, packages/configs/src/prisma/queries/init/windowCenter.ts, packages/configs/src/prisma/queries/write.ts, packages/configs/src/server.ts, packages/schema/src/WindowCenter.graphql, packages/ui/src/components/Panels/Guider/Guider.scss, packages/ui/src/components/Panels/Guider/WavefrontSensors/ACHR.tsx, packages/ui/src/components/Panels/Guider/WavefrontSensors/WavefrontSensors.tsx, packages/ui/src/gql/configs/WindowCenter.ts, packages/ui/src/gql/server/AcquisitionCamera.ts
=> Add AC/HRWFS controls

packages/configs/src/graphql/resolvers/Instrument.ts, packages/schema/src/Instrument.graphql, packages/ui/src/components/Contexts/Variables/Modals/Catalog/Catalog.tsx, packages/ui/src/components/Contexts/Variables/Modals/Instrument.tsx, packages/ui/src/components/Contexts/Variables/Modals/Modals.css, packages/ui/src/components/Contexts/Variables/Modals/OdbImport/OdbImport.tsx, packages/ui/src/components/Contexts/Variables/Modals/Target.tsx, packages/ui/src/components/Icons.tsx, packages/ui/src/components/Layout/AcquisitionAdjustmentToast.css, packages/ui/src/components/Layout/AcquisitionAdjustmentToast.tsx, packages/ui/src/components/Panels/Telescope/Systems/Instrument.test.tsx, packages/ui/src/components/Panels/Telescope/Systems/Instrument.tsx, packages/ui/src/components/Panels/Telescope/Telescope.css, packages/ui/src/gql/configs/Instrument.ts, packages/ui/src/main.tsx
https://github.com/user-attachments/assets/552b27c4-8b64-4992-b1bb-5921dbdf214b
=> Add instrument history and ability to delete instruments, and comment when saving an instrument.

packages/ui/src/components/Contexts/Variables/Modals/Instrument.tsx, packages/ui/src/components/Layout/Navbar/Navbar.tsx, packages/ui/src/components/Panels/WavefrontSensors/AcquisitionCamera/Controls.tsx, packages/ui/src/components/Panels/WavefrontSensors/AcquisitionCamera/InstrumentHandset.tsx, packages/ui/src/components/Panels/WavefrontSensors/AcquisitionCamera/MainControls.tsx, packages/ui/src/components/Panels/WavefrontSensors/AcquisitionCamera/TargetsHandset.test.tsx, packages/ui/src/components/Panels/WavefrontSensors/AcquisitionCamera/TargetsHandset.tsx, packages/ui/src/components/atoms/theme.test.ts, packages/ui/src/components/atoms/theme.ts
- **Update theme atom**
- **Change order of handsets**
- **Change label of Open Loops**
- **Change default open loops to true**
- **Keep state of handset when switching tabs'**
- **Use promise.all**
- **Update test**
=> sc 6844 handset improvements
